name: Build and Test

on:
  pull_request:
  push:
    branches:
      - "actions"

permissions:
  contents: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup LLVM (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 16 all
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-16 160
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-16 160
          sudo update-alternatives --install /usr/bin/lli lli /usr/bin/lli-16 160

      - name: Setup LLVM (MacOS)
        if: ${{ runner.os == 'macOS' }}
        run: |
          brew install llvm@16
          echo "$(brew --prefix llvm@16)/bin" >> $GITHUB_PATH
          echo "CC=$(brew --prefix llvm@16)/bin/clang" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix llvm@16)/bin/clang++" >> $GITHUB_ENV

      - name: Install PyTest
        run: |
          printenv
          pip install pytest pytest-xdist
          echo '${{ env.PYTHONUSERBASE }}/bin/' >> $GITHUB_PATH

      - name: Build
        run: |
          mkdir build
          cmake -S . -B build -DLLVM_INCLUDE_TESTS=On
          cmake --build build

      - name: Test
        run: pytest -n 32

# The llvm-dev package doesn't exist for Windows, so we need to build LLVM ourselves.
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout LLVM
        uses: actions/checkout@master
        with:
          repository: llvm/llvm-project
          ref: llvmorg-16.0.6

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/llvm/projects/llvm-cbe

      - name: Install PyTest
        run: |
          pip install pytest pytest-xdist
          echo '${{ env.PYTHONUSERBASE }}/bin/' >> $GITHUB_PATH

      - name: Build
        run: |
          mkdir build
          cmake -S llvm -B build -G Ninja -DLLVM_INCLUDE_TESTS=On -DCMAKE_BUILD_TYPE=RelWithDebInfo
          ninja -C build llvm-tablegen
          ninja -C build lli
          ninja -C build llvm-cbe

      - name: Test
        run: pytest -n 32